name: Failure Tests
on:
  push:
    branches: [ release/*, develop ]
jobs:
  one:
    runs-on: [self-hosted, macOS]
    steps:
      - name: command failure
        id: command-failure
        uses: ./
        with:
          anka-template: "10.15.5"
          anka-tag: "base"
          anka-run-options: "-n"
          commands: "java -version || if [ \\$? -gt 0 ]; then echo failed; else exit 20; fi"
  two:
    runs-on: [self-hosted, macOS]
    steps:
      - name: multi-line commands failure
        id: multi-line-commands-failure
        uses: ./
        with:
          anka-template: "10.15.5"
          anka-tag: "base"
          anka-run-options: "-n"
          commands: |
            echo 123
            java -version || if [ \$? -gt 0 ]; then echo failed; else exit 20; fi
  # Cannot throw a pass if it fails so we'll just use a unit test for now
  # two:
  #   runs-on: [self-hosted, macOS]
  #   steps:
  #     - name: bad host command option
  #       id: bad-host-command-option
  #       uses: ./
  #       with:
  #         anka-template: "10.15.5"
  #         anka-tag: "base"
  #         anka-run-options: "-n"
  #         host-command-options: "1231!!"
  #         commands: "echo 123"